###
GET http://127.0.0.1:8000/api/roles
###
POST http://127.0.0.1:8000/api/roles
Content-Type: application/json

  {
    "login": "33333 ZZZZZZZZ@gmail.com",
    "pwd": "123",
    "nom": "ZZZZZZ Alain Pilon",
    "date": "2022-10-25T04:00:00.000Z",
    "roles": [
      "rien",
      "rien2",
      "rien3",
      "rien4"
    ]
  }
