###
GET http://127.0.0.1:8000/api/livres
###
GET http://127.0.0.1:8000/api/livres/titre/A
###
GET http://127.0.0.1:8000/api/livres/auteur/Steve
###
GET http://127.0.0.1:8000/api/livres/isbn/403
###
GET http://127.0.0.1:8000/api/livres/description/homme
###
POST http://127.0.0.1:8000/api/livres
Content-Type: application/json

{
    "auteur": "Steve Caillou",
    "titre": "111 mon beau livre",
    "description": "Bla bla bla",
    "editeur": "Kekchose",
    "nbPage": 9832,
    "langue": "Français/French",
    "isbn": "123456",
    "prix": 999.99
}
### 
DELETE http://127.0.0.1:8000/api/livres/12345339
### 
DELETE http://127.0.0.1:8000/api/livres/123456
###
PUT http://127.0.0.1:8000/api/livres/123456
Content-Type: application/json

  {
    "titre": "888 mon beau livre",
    "auteur": "Steve Caillou",
    "editeur": "Kekchose",
    "langue": "Français/French",
    "isbn": "123456",
    "prix": 1.29,
    "description": "AAAAAAAAAAAAAAAAA",
    "nbPage": 132
  }
###
GET http://127.0.0.1:8000/api/users
###
POST http://127.0.0.1:8000/api/users
Content-Type: application/json

{
    "login": "AAAAJo@gmail.com",
    "pwd": "AAAA123",
    "nom": "AAA Jo"
}
###
DELETE http://127.0.0.1:8000/api/users/aaa@gmail.com
###
PUT http://127.0.0.1:8000/api/users/AAAAJo@gmail.com
Content-Type: application/json

  {
    "login": "YYYYYYYYY@gmail.com",
    "pwd": "YYY",
    "nom": "Toto Jo"
  }
###
GET http://127.0.0.1:8000/api/users/login/AAA
###
GET http://127.0.0.1:8000/api/users/nom/Fred